backend:
  name: git-gateway
  branch: main

media_folder: public/Image
public_folder: /Image

collections:
  - name: "projects"
    label: "Projects"
    folder: "src/content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title",       name: "title",  widget: "string" }
      - { label: "Description", name: "desc",   widget: "text" }
      - { label: "Tag",         name: "tag",    widget: "select", options: ["WEBSITE", "MOBILE APP", "POS", "REDESIGN"] }
      - { label: "Image",       name: "img",    widget: "image" }
      - { label: "Figma Link",  name: "figma",  widget: "string" }
      - { label: "Date",        name: "date",   widget: "datetime" }