backend:
  name: git-gateway
  branch: main

media_folder: "public/image"
public_folder: "/image"

collections:
  - name: "projects"
    label: "Projects"
    folder: "src/content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title",       name: "title",  widget: "string" }
      - { label: "Description", name: "desc",   widget: "text" }
      - label: "Tags"
        name: "tags"
        widget: "list"
        allow_add: true
        minimal: true
        field:
          name: "tag"
          widget: "string"
      - { label: "Image",       name: "img",    widget: "image" }
      - { label: "Figma Link",  name: "figma",  widget: "string" }
      - { label: "Date",        name: "date",   widget: "datetime" }